export const BUTTON_CLICKED = 'BUTTON_CLICKED';
export const ON_COLLAPSIBLE_CLICKED = 'ON_COLLAPSIBLE_CLICKED';
export const FETCH_DATA_FULFILLED = 'FETCH_DATA_FULFILLED';
export const FETCH_DATA_REJECTED = 'FETCH_DATA_REJECTED';